#!/usr/bin/env bash
# secure transfering of file to server

#checking whether the four requirement is fullfilled

if [ $# -lt 4 ]
then 	
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#securely sending file to server by disabling StrictHostKeyChecking

path_to_file=$1
ip=$2
username=$3
path_to_key=$4

scp -o "StrictHostKeyChecking no" -i "$path_to_file" "$path_to_key" "$username@$ip:~/"

if [ $? -eq 0 ]
then
	echo "transferred"
else
	echo "Not transferred"
fi
