#!/usr/bin/env bash
#display hour from 0-12
#display minute from 1-59
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ $min -le 59 ]
	do 
		echo "$min"
	(( min++ ))
	done
	(( hour++))
done 
